FROM openjdk:8-jre-alpine
ENV TZ=Asia/Shanghai LANG="C.UTF-8"
#below 3 lines cause failure cause alphine does not have the file /etc/localtime !
#RUN \
#    rm /etc/localtime && \
#    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN echo -e "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main\n\
https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" > /etc/apk/repositories

RUN apk --update add curl bash ttf-dejavu && \
      rm -rf /var/cache/apk/*

# copy jar from the first stage
ADD target/destroyer-api.jar app.jar
# run jar
CMD ["java", "-jar", "app.jar"]