# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 30
  port: 18888
  connection-timeout: 5000
  context-path: /

spring:
#  autoconfigure: #忽略mongo自动配置
#    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  application:
    name: pdd-api
  # 环境 dev|test|pro
  profiles:
    active: @spring.profiles.active@
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
    #resources: # 指定静态资源的路径
    #static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mex.pdd.modules.admin.sys.entity,com.mex.pdd.modules.api.entity
  typeEnumsPackage: com.mex.pdd.base.common.enums
  #  typeHandlersPackage: com.mex.cpa.base.common.utils.mybatis
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: cn.jeefast.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level: debug
app:
  oss:
    domain: https://res.minigames.ad-mex.com/
    endpoint: http://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAIGxdrA6p2yz8N
    accessKeySecret: eTgIKy10kNm4OIIWFkp5Xv14Rt8y1N
    bucketName: minigames
    prefix: destroyer
    downloadDir: /data/log/destroyer
management:
  security:
    enabled: false
